# Generated by Django 2.2.4 on 2019-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190808_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_resolved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Resolved ?'),
        ),
    ]
